version: '3'

services:
    db:
        image: mysql:latest
        restart: always
        
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./db_data:/var/lib/mysql
        ports: 
            - "3306:3306"

    adminer:
        image: adminer
        depends_on: 
            - db
        restart: always
        ports:
            - 8080:8080
    
    users:
        image: users:${TAG:-latest}
        build:
            context: ./users-microservice/
            dockerfile: Dockerfile
        restart: always
        depends_on: 
            - db
        environment: 
            PORT: 3001
            DB_HOST: 'db'
            DB_USER : ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_DATABASE: ${DB_DATABASE}
            DB_PORT: ${DB_PORT}

        ports: 
            - "3001:3001"
    
    agenda:
        image: agenda:${TAG:-latest}
        build:
            context: ./agenda-microservice/
            dockerfile: Dockerfile
        restart: always
        depends_on: 
            - db
        environment: 
            PORT: 3002
            DB_HOST: 'db'
            DB_USER : ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_DATABASE: ${DB_DATABASE}
            DB_PORT: ${DB_PORT}

        ports: 
            - "3002:3002"
    
        